import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Worksheet } from '../types';

export const generatePDF = async (worksheet: Worksheet, includeAnswers: boolean = false) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Title
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Singapore Math Worksheet', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Worksheet details
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Level: ${worksheet.level}`, margin, yPosition);
  pdf.text(`Topic: ${worksheet.topic}`, margin + 60, yPosition);
  pdf.text(`Difficulty: ${worksheet.difficulty}`, margin + 120, yPosition);
  yPosition += 20;

  // Questions
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Questions:', margin, yPosition);
  yPosition += 15;

  pdf.setFont('helvetica', 'normal');
  worksheet.questions.forEach((question, index) => {
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = margin;
    }

    pdf.text(`${index + 1}. ${question.question}`, margin, yPosition);
    yPosition += 15;

    if (includeAnswers) {
      pdf.setFont('helvetica', 'italic');
      pdf.text(`Answer: ${question.answer}`, margin + 10, yPosition);
      yPosition += 10;
      
      if (question.workingSteps && question.workingSteps.length > 0) {
        pdf.text('Working:', margin + 10, yPosition);
        yPosition += 8;
        question.workingSteps.forEach(step => {
          pdf.text(`• ${step}`, margin + 20, yPosition);
          yPosition += 8;
        });
      }
      pdf.setFont('helvetica', 'normal');
      yPosition += 5;
    } else {
      yPosition += 10;
    }
  });

  // Footer
  const footerY = pdf.internal.pageSize.getHeight() - 20;
  pdf.setFontSize(10);
  pdf.text('Generated by Singapore Math Worksheet Generator', pageWidth / 2, footerY, { align: 'center' });

  return pdf;
};

export const downloadWorksheet = async (worksheet: Worksheet, includeAnswers: boolean = false) => {
  const pdf = await generatePDF(worksheet, includeAnswers);
  const filename = `${worksheet.level}_${worksheet.topic}_${worksheet.difficulty}_${includeAnswers ? 'with_answers' : 'questions'}.pdf`;
  pdf.save(filename);
};
